import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDB } from '../config/db';
import { logger } from '../config/logger';
import { User } from '../models/User';
import { Hospital } from '../models/Hospital';
import { BloodRequest } from '../models/BloodRequest';
import { BloodInventory } from '../models/BloodInventory';
import { Doctor } from '../models/Doctor';
import { CommunityGroup } from '../models/CommunityGroup';
import { CommunityPost } from '../models/CommunityPost';
import { MedicineInventory } from '../models/MedicineInventory';
import { SupplyRequest } from '../models/SupplyRequest';
import { Course, Enrollment, Certification } from '../models/Training';
import { Medication, Allergy, Vaccination, Appointment, Condition, Disability } from '../models/HealthRecord';
import { Emergency } from '../models/Emergency';
import { DoctorApplication } from '../models/DoctorApplication';
import { trainingCourses } from './trainingCourses';
import { randomBytes } from 'crypto';
import { GridFSBucket } from 'mongodb';

// Minimal valid 1-page PDF written by hand. Renders the given text via the
// standard Helvetica font; xref offsets are computed at write time.
const buildDemoPdf = (name: string, specialty: string, years: number): Buffer => {
  const lines = [
    'VITALIS DEMO ARTIFACT',
    '',
    `Holder: ${name}`,
    `Specialty: ${specialty}`,
    `Years of experience: ${years}`,
    '',
    'This is a placeholder credential generated by the Vitalis seed',
    'script for demo purposes. It is not a real medical certification.',
  ];
  const stream = [
    'BT',
    '/F1 14 Tf',
    '72 760 Td',
    `(${lines[0]}) Tj`,
    '0 -28 TD',
    '/F1 11 Tf',
    ...lines.slice(1).map((l) => `(${l.replace(/[()\\]/g, (c) => '\\' + c)}) Tj 0 -16 TD`),
    'ET',
  ].join('\n');
  const streamBuf = Buffer.from(stream, 'binary');

  const objects: string[] = [];
  objects.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj');
  objects.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj');
  objects.push(
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ' +
      '/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >> endobj'
  );
  objects.push(
    `4 0 obj << /Length ${streamBuf.length} >> stream\n${stream}\nendstream endobj`
  );
  objects.push('5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj');

  const header = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
  const offsets: number[] = [];
  let body = '';
  let cursor = Buffer.byteLength(header, 'binary');
  for (const obj of objects) {
    offsets.push(cursor);
    body += obj + '\n';
    cursor += Buffer.byteLength(obj + '\n', 'binary');
  }
  const xrefStart = cursor;
  let xref = `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) {
    xref += off.toString().padStart(10, '0') + ' 00000 n \n';
  }
  const trailer = `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
  return Buffer.from(header + body + xref + trailer, 'binary');
};

const BLOOD_TYPES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] as const;

// Tirana coords for demo
const TIRANA: [number, number] = [19.8189, 41.3275];
const jitter = (c: [number, number], r = 0.03): [number, number] =>
  [c[0] + (Math.random() - 0.5) * r, c[1] + (Math.random() - 0.5) * r];

async function seed() {
  await connectDB();

  logger.info('Clearing collections…');
  await Promise.all([
    Hospital.deleteMany({}),
    BloodRequest.deleteMany({}),
    BloodInventory.deleteMany({}),
    Doctor.deleteMany({}),
    CommunityGroup.deleteMany({}),
    CommunityPost.deleteMany({}),
    MedicineInventory.deleteMany({}),
    SupplyRequest.deleteMany({}),
    Course.deleteMany({}),
    Enrollment.deleteMany({}),
    Certification.deleteMany({}),
    User.deleteMany({}),
    Medication.deleteMany({}),
    Allergy.deleteMany({}),
    Vaccination.deleteMany({}),
    Appointment.deleteMany({}),
    Condition.deleteMany({}),
    Disability.deleteMany({}),
    Emergency.deleteMany({}),
    DoctorApplication.deleteMany({}),
  ]);

  logger.info('Seeding admin + demo users…');
  await User.create({
    email: 'aleks@vitalis.com',
    password: 'AlexNo11$',
    firstName: 'Aleks',
    lastName: 'Admin',
    name: 'Aleks Admin',
    role: 'admin',
  });

  const demoCitizen = await User.create({
    email: 'demo@vitalis.com',
    password: 'Demo1234!',
    firstName: 'Elena',
    lastName: 'Demo',
    name: 'Elena Demo',
    role: 'citizen',
    bloodType: 'O+',
    age: 29,
    gender: 'female',
    heightCm: 168,
    weightKg: 62,
    illnesses: ['Asthma (mild)'],
    disabilities: [],
  });

  await User.create({
    email: 'dispatcher@vitalis.com',
    password: 'Dispatch1!',
    firstName: 'Mark',
    lastName: 'Ops',
    name: 'Mark Ops',
    role: 'dispatcher',
  });

  const doctorApplicantUser = await User.create({
    email: 'applicant@vitalis.com',
    password: 'Applicant1!',
    firstName: 'Jana',
    lastName: 'Applicant',
    name: 'Jana Applicant',
    role: 'citizen',
  });

  // Hospitals
  logger.info('Seeding hospitals…');
  const hospitals = await Hospital.insertMany([
    { name: 'Mother Teresa University Hospital', type: 'public', address: 'Rruga e Dibrës, Tirana', phone: '+355 4 222 2222', isOpen24h: true, location: { type: 'Point', coordinates: jitter(TIRANA) } },
    { name: 'American Hospital 1', type: 'private', address: 'Rruga e Kavajës, Tirana', phone: '+355 4 240 1234', isOpen24h: true, location: { type: 'Point', coordinates: jitter(TIRANA) } },
    { name: 'Hygeia Hospital', type: 'private', address: 'Rruga Janos Hunyadi, Tirana', phone: '+355 4 290 3000', isOpen24h: true, location: { type: 'Point', coordinates: jitter(TIRANA) } },
    { name: 'Memorial Hospital', type: 'private', address: 'Rruga e Durrësit, Tirana', phone: '+355 4 232 4444', isOpen24h: false, location: { type: 'Point', coordinates: jitter(TIRANA) } },
  ]);

  // Blood inventory: each hospital, each type
  logger.info('Seeding blood inventory…');
  const inv: any[] = [];
  for (const h of hospitals) {
    for (const t of BLOOD_TYPES) {
      const available = Math.floor(Math.random() * 30);
      const needed = Math.random() < 0.25 ? available + Math.floor(Math.random() * 8) + 1 : 0;
      inv.push({ hospital: h._id, bloodType: t, unitsAvailable: available, unitsNeeded: needed });
    }
  }
  await BloodInventory.insertMany(inv);

  // Blood requests
  logger.info('Seeding blood requests…');
  const requests = [
    { hospital: hospitals[0]._id, patientName: 'Anonymous patient #A-204', bloodType: 'O-' as const, urgency: 'critical' as const, unitsNeeded: 4, reason: 'Emergency transfusion post-trauma' },
    { hospital: hospitals[1]._id, patientName: 'Anonymous patient #B-118', bloodType: 'AB-' as const, urgency: 'urgent' as const, unitsNeeded: 2, reason: 'Scheduled surgery' },
    { hospital: hospitals[2]._id, patientName: 'Anonymous patient #C-307', bloodType: 'A+' as const, urgency: 'normal' as const, unitsNeeded: 1, reason: 'Chronic anemia' },
    { hospital: hospitals[0]._id, patientName: 'Anonymous patient #A-301', bloodType: 'B+' as const, urgency: 'urgent' as const, unitsNeeded: 3, reason: 'Postpartum hemorrhage' },
  ];
  await BloodRequest.insertMany(requests);

  logger.info('Seeding medicine inventory…');
  await MedicineInventory.insertMany([
    {
      pharmacy: { name: 'Central Pharmacy', phone: '+355 4 555 1100' },
      medicine: { name: 'Human Albumin 20%', atc: 'B05AA01' },
      stock: 3,
      rare: true,
      location: { type: 'Point', coordinates: jitter(TIRANA) },
    },
    {
      pharmacy: { name: 'CarePlus Tirana', phone: '+355 4 555 1101' },
      medicine: { name: 'Factor VIII Concentrate', atc: 'B02BD02' },
      stock: 2,
      rare: true,
      location: { type: 'Point', coordinates: jitter(TIRANA) },
    },
    {
      pharmacy: { name: 'University Hospital Pharmacy', phone: '+355 4 555 1102' },
      medicine: { name: 'Immunoglobulin IV', atc: 'J06BA02' },
      stock: 5,
      rare: true,
      location: { type: 'Point', coordinates: jitter(TIRANA) },
    },
    {
      pharmacy: { name: 'MedLife Pharmacy', phone: '+355 4 555 1103' },
      medicine: { name: 'Amoxicillin 500mg', atc: 'J01CA04' },
      stock: 42,
      rare: false,
      location: { type: 'Point', coordinates: jitter(TIRANA) },
    },
  ]);

  logger.info('Seeding supply exchange requests…');
  await SupplyRequest.insertMany([
    {
      category: 'organ',
      title: 'Urgent kidney transplant coordination',
      resourceType: 'Kidney',
      urgency: 'critical',
      quantityLabel: '1 matched donor',
      facilityName: hospitals[0].name,
      notes: 'Recipient prepared and cross-match window is open.',
    },
    {
      category: 'tissue',
      title: 'Corneal tissue request',
      resourceType: 'Cornea',
      urgency: 'urgent',
      quantityLabel: '2 grafts',
      facilityName: hospitals[1].name,
      notes: 'Needed for scheduled ophthalmic procedures this week.',
    },
    {
      category: 'medicine',
      title: 'Rare immunoglobulin stock request',
      resourceType: 'Immunoglobulin IV',
      urgency: 'urgent',
      quantityLabel: '4 vials',
      facilityName: hospitals[2].name,
      notes: 'Pediatric immunology case awaiting confirmation.',
    },
    {
      category: 'blood',
      title: 'Critical O- emergency stock transfer',
      resourceType: 'O- blood',
      urgency: 'critical',
      quantityLabel: '4 units',
      facilityName: hospitals[0].name,
      notes: 'Transfer support requested for trauma stabilization.',
    },
  ]);

  // Doctors
  logger.info('Seeding doctors…');
  const doctors = [
    { name: 'Dr. Elena Hoxha', specialty: 'Cardiology', hospital: hospitals[0]._id, experience: 12, rating: 4.9, reviewCount: 142, priceConsultation: 4500, availableOnline: true, availableNow: true, phone: '+355691234567', biography: 'Interventional cardiologist with focus on acute coronary syndromes.' },
    { name: 'Dr. Andi Berisha', specialty: 'Neurology', hospital: hospitals[1]._id, experience: 9, rating: 4.7, reviewCount: 88, priceConsultation: 5000, availableOnline: true, availableNow: false, phone: '+355691234567', biography: 'Headache and stroke specialist.' },
    { name: 'Dr. Lorena Marku', specialty: 'Pediatrics', hospital: hospitals[2]._id, experience: 7, rating: 4.8, reviewCount: 201, priceConsultation: 3500, availableOnline: true, availableNow: true, phone: '+355691234567', biography: 'Pediatrician — newborn to adolescent care.' },
    { name: 'Dr. Mark Gjoka', specialty: 'Orthopedics', hospital: hospitals[3]._id, experience: 15, rating: 4.6, reviewCount: 67, priceConsultation: 6000, availableOnline: false, availableNow: false, biography: 'Sports injuries and joint replacement.' },
    { name: 'Dr. Sara Çela', specialty: 'Dermatology', hospital: hospitals[1]._id, experience: 8, rating: 4.9, reviewCount: 156, priceConsultation: 4000, availableOnline: true, availableNow: true, phone: '+355691234567', biography: 'Skin oncology and cosmetic dermatology.' },
    { name: 'Dr. Petrit Doku', specialty: 'Endocrinology', hospital: hospitals[2]._id, experience: 11, rating: 4.7, reviewCount: 92, priceConsultation: 4500, availableOnline: true, availableNow: false, phone: '+355691234567', biography: 'Diabetes and thyroid disorders.' },
    { name: 'Dr. Ina Lleshi', specialty: 'Gastroenterology', hospital: hospitals[0]._id, experience: 10, rating: 4.5, reviewCount: 54, priceConsultation: 5500, availableOnline: false, availableNow: false, biography: 'GI endoscopy and liver disease.' },
    { name: 'Dr. Klodian Rama', specialty: 'Psychology', hospital: hospitals[1]._id, experience: 6, rating: 4.9, reviewCount: 178, priceConsultation: 3000, availableOnline: true, availableNow: true, phone: '+355691234567', biography: 'Anxiety, depression, CBT.' },
  ];
  await Doctor.insertMany(doctors);

  // Community groups
  logger.info('Seeding community groups…');
  const groups = await CommunityGroup.insertMany([
    { name: 'Living with Diabetes', description: 'Daily tips, recipes, glucose management.', category: 'diabetes', memberCount: 2842 },
    { name: 'Cancer Survivors', description: 'Support network for patients and families.', category: 'cancer', memberCount: 1276 },
    { name: 'Anxiety & Mental Health', description: 'A safe space to talk and listen.', category: 'anxiety', memberCount: 4521 },
    { name: 'New Parents', description: 'Newborn care, sleep, feeding.', category: 'parents', memberCount: 3104 },
    { name: 'Student Health', description: 'For university students balancing studies and wellbeing.', category: 'students', memberCount: 1893 },
    { name: 'Heart Health', description: 'Cardiac patients and prevention.', category: 'heart', memberCount: 982 },
    { name: 'Autoimmune Warriors', description: 'Lupus, MS, Crohn’s and more.', category: 'autoimmune', memberCount: 743 },
    { name: 'Rare Diseases', description: 'Connecting patients with rare conditions.', category: 'rare', memberCount: 412 },
  ]);

  // Community posts (a couple per group)
  logger.info('Seeding community posts…');
  const posts: any[] = [];
  const samplePosts = [
    'Just got my A1C results — down 0.8 points since switching to lower-carb breakfasts. Anyone else found small changes that stuck?',
    'Three months post-chemo and the fatigue is still real. How long did it take you to feel like yourself again?',
    'Therapist gave me a great grounding technique today — 5 things you see, 4 you hear, 3 you can touch, 2 you smell, 1 you taste. It actually helped during a panic spike.',
    'Tip for new parents: a white-noise machine changed everything for our 4-month-old.',
    'Anyone here juggling med school and a chronic condition? Looking for organisation tips.',
    'Started a 20-minute morning walk after my cardiologist appointment. Resting BPM dropped 6 points in three weeks.',
    'Anyone else here tracking their meds in Vitalis? Love that responders can see them if I ever pass out.',
    'New flare-up this week. Heat packs and the breathing exercise from the CPR course (weirdly) help me stay calm.',
    'My kid finally slept through the night 🙏 — turns out the issue was their room being too warm.',
    'Pro tip for med students: 3-2-1 rule — 3 hours focused study, 2 hours rest, 1 hour movement. Sleep > caffeine, always.',
    'Just earned my CPR cert in the Training tab! Highly recommend, it took me about 25 minutes.',
    'Honest question: anyone else find SOS reassuring even when they never use it? Just knowing it is one tap away.',
  ];
  const sampleAuthors = ['Sara K.', 'Andi P.', 'Lena M.', 'Tomas R.', 'Marin V.', 'Jovi S.', 'Ada D.', null];
  groups.forEach((g, i) => {
    for (let k = 0; k < 4; k++) {
      const idx = (i * 3 + k) % samplePosts.length;
      const author = sampleAuthors[(i + k) % sampleAuthors.length];
      posts.push({
        group: g._id,
        authorName: author ?? undefined,
        isAnonymous: !author,
        content: samplePosts[idx],
        likes: 4 + Math.floor(Math.random() * 90),
        commentsCount: Math.floor(Math.random() * 18),
      });
    }
  });
  await CommunityPost.insertMany(posts);

  logger.info('Seeding training courses…');
  const seededCourses = await Course.insertMany(trainingCourses);
  const cprCourse = seededCourses.find((c) => c.slug === 'cpr-adult');

  logger.info('Seeding demo citizen Bio Passport…');
  await Medication.insertMany([
    { user: demoCitizen._id, name: 'Salbutamol inhaler', dosage: '100 mcg, 2 puffs as needed', isActive: true },
    { user: demoCitizen._id, name: 'Vitamin D3', dosage: '1000 IU daily', isActive: true },
  ]);
  await Allergy.insertMany([
    { user: demoCitizen._id, allergen: 'Penicillin', severity: 'severe' },
    { user: demoCitizen._id, allergen: 'Peanuts', severity: 'moderate' },
    { user: demoCitizen._id, allergen: 'Pollen', severity: 'mild' },
  ]);
  await Vaccination.insertMany([
    { user: demoCitizen._id, name: 'COVID-19 booster', date: new Date('2025-09-12'), provider: 'University Hospital' },
    { user: demoCitizen._id, name: 'Tetanus (Td)', date: new Date('2022-03-04'), provider: 'Central Pharmacy' },
    { user: demoCitizen._id, name: 'Influenza', date: new Date('2025-10-18'), provider: 'CarePlus Tirana' },
  ]);
  await Condition.insertMany([
    { user: demoCitizen._id, name: 'Asthma (mild)', notes: 'Triggered by cold air and exercise; managed with inhaler.' },
  ]);
  await Disability.insertMany([
    { user: demoCitizen._id, name: 'Mild colour vision deficiency', notes: 'Red-green spectrum. Helpful to mention before any visual triage test.' },
  ]);
  await Appointment.insertMany([
    {
      user: demoCitizen._id,
      appointmentType: 'checkup',
      scheduledAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      status: 'scheduled',
      notes: 'Annual asthma review — bring inhaler usage log.',
    },
    {
      user: demoCitizen._id,
      appointmentType: 'consultation',
      scheduledAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000),
      status: 'completed',
      notes: 'Dermatology follow-up — clear.',
    },
  ]);

  if (cprCourse) {
    logger.info('Seeding demo citizen CPR certification…');
    await Enrollment.create({
      user: demoCitizen._id,
      course: cprCourse._id,
      completedLessonIds: cprCourse.lessons?.map((l: any) => l._id) ?? [],
      lastScore: 88,
      attempts: 1,
      completedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    });
    await Certification.create({
      user: demoCitizen._id,
      course: cprCourse._id,
      courseSlug: cprCourse.slug,
      badgeLabel: cprCourse.badgeLabel,
      score: 88,
      issuedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
      expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
      shareToken: randomBytes(12).toString('hex'),
    });
  }

  logger.info('Seeding demo SOS history…');
  await Emergency.create({
    citizen: demoCitizen._id,
    type: 'medical',
    priority: 2,
    status: 'resolved',
    description: 'Severe allergic reaction at café — resolved by responder, transported to hospital.',
    location: { type: 'Point', coordinates: jitter(TIRANA, 0.01) },
    etaSeconds: 240,
    timeline: [
      { status: 'pending', at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000) },
      { status: 'assigned', at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000 + 90 * 1000) },
      { status: 'on_scene', at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000 + 360 * 1000) },
      { status: 'resolved', at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000 + 2400 * 1000) },
    ],
  });

  logger.info('Seeding pending doctor applications with real PDFs in GridFS…');
  const bucket = new GridFSBucket(mongoose.connection.db!, { bucketName: 'doctorCerts' });
  // Drop any existing seeded PDFs from prior seed runs.
  try { await mongoose.connection.db!.collection('doctorCerts.files').deleteMany({}); } catch {}
  try { await mongoose.connection.db!.collection('doctorCerts.chunks').deleteMany({}); } catch {}

  const uploadCertPdf = async (filename: string, name: string, specialty: string, years: number) => {
    const buf = buildDemoPdf(name, specialty, years);
    return new Promise<mongoose.Types.ObjectId>((resolve, reject) => {
      const stream = bucket.openUploadStream(filename, { contentType: 'application/pdf' });
      stream.on('finish', () => resolve(stream.id as unknown as mongoose.Types.ObjectId));
      stream.on('error', reject);
      stream.end(buf);
    });
  };

  const apps = [
    {
      user: doctorApplicantUser._id,
      fullName: 'Dr. Jana Applicant',
      email: 'applicant@vitalis.com',
      phone: '+355692345678',
      specialty: 'Pediatric Cardiology',
      yearsExperience: 6,
      bio: 'Pediatric cardiologist, 6 years at University Hospital — focus on congenital heart defects and post-op follow up. Looking to extend remote consultations to families in rural areas.',
      certificateFilename: 'jana-applicant-specialty-cert.pdf',
      status: 'pending',
    },
    {
      user: doctorApplicantUser._id,
      fullName: 'Dr. Tomas Reka',
      email: 'tomas.reka@example.com',
      phone: '+355693456789',
      specialty: 'Emergency Medicine',
      yearsExperience: 11,
      bio: 'ER attending physician, also trains paramedics for ambulance services. Wants to be visible to dispatchers during mass-casualty incidents.',
      certificateFilename: 'tomas-reka-em-board-cert.pdf',
      status: 'pending',
    },
    {
      user: doctorApplicantUser._id,
      fullName: 'Dr. Marin Vata',
      email: 'marin.vata@example.com',
      phone: '+355694567890',
      specialty: 'Psychiatry',
      yearsExperience: 8,
      bio: 'Adult psychiatrist with telehealth experience — CBT, trauma-informed care, anxiety and depression. Open to anonymous triage on the Community tab.',
      certificateFilename: 'marin-vata-psych-cert.pdf',
      status: 'pending',
    },
  ];

  for (const a of apps) {
    const fileId = await uploadCertPdf(a.certificateFilename, a.fullName, a.specialty, a.yearsExperience);
    await DoctorApplication.create({ ...a, certificateFileId: fileId });
  }

  logger.info('✅ Seed complete.');
  await mongoose.disconnect();
}

seed().catch(err => {
  logger.error('Seed failed', err);
  process.exit(1);
});
